// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iscqwjjttvgxeehxggxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzY3F3amp0dHZneGVlaHhnZ3hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyOTM5MjksImV4cCI6MjA1NDg2OTkyOX0.R2MwFmfrpwrgD2-DkNwPY3iabdWCph57pmZXv_Ms84E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);